config/routes.rb
Rails.application.routes.draw do
  get 'feed' => 'epicenter#feed'
  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'
  get 'tag_tweets' => 'epicenter#tag_tweets'

  get 'all_users' => 'epicenter#all_users'

  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'
  resources :tweets
  devise_for :users
  root 'epicenter#feed'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user

	has_many :tweet_tags
	has_many :tags, through: :tweet_tags

	before_validation :link_check, on: :create

	validates :message, presence: true
	validates :message, length: {maximum: 140, too_long: "maximum of 140 characters"}

	after_validation :apply_link, on: :create

private

	def link_check
		if self.message.include? "https://"
			arr = self.message.split
			index = arr.map {|x| x.include? "https://"}.index(true)

			self.link = arr[index]

			if arr[index].length > 20
				arr[index] = "#{arr[index][0..18]}..."
			end

			self.message = arr.join(" ")
		end
	end
	def apply_link
		arr = self.message.split
		index = arr.map {|x| x.include? "https://"}.index(true)
		if index
			url = arr[index]
			arr[index] = "<a href='#{self.link}'>#{url}</a>"
		end
		self.message = arr.join(" ")
	end
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
	belongs_to :tweet
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets

  serialize :following, Array

  validates :username, presence: true, uniqueness: true
  validates :name, presence: true

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

	# before_action :authenticate_user!
	
	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location])
		devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar])
	end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  def feed
  	@following_tweets = []
  	if current_user == nil
  		return
  	end
  	Tweet.all.each do |tweet|
      if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id
        @following_tweets.push(tweet)
      end
    end
  end

  def show_user
  	@user = User.find(params[:id])
    @tweets = []
    Tweet.all.each do |tweet|
      if tweet.user_id == @user.id
        @tweets.push(tweet)
      end
    end
  end

  def now_following
    # We are adding the user.id of the user you want to 
    # follow to your following array.
    # and we want to make sure it's saved in there as an integer
    current_user.following.push(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def unfollow
  	current_user.following.delete(params[:id].to_i)
  	current_user.save

  	redirect_to show_user_path(id: params[:id])
  end
  def tag_tweets
    @tag = Tag.find(params[:id])
  end
  def all_users
    @users = User.all
  end
  def following
    @interested_user = User.find(params[:id])

    @users = []
    User.all.each do |user|
      if @interested_user.following.include?(user.id)
        @users.push(user)
      end
    end
  end
  def followers
    @interested_user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if user.following.include?(@interested_user.id)
        @users.push(user)
      end
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  include TweetsHelper
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)

    @tweet = get_tagged(@tweet)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
	def get_tagged(tweet)
		message_arr = tweet.message.split

    	message_arr.each_with_index do |word, index|
     	if word[0] == '#'
       		if Tag.pluck(:phrase).include?(word)
         		tag = Tag.find_by(phrase: word)
        	else
         		tag = Tag.create(phrase: word)
        	end
        	tweet_tag = TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
        	message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
      	end
    	end

    tweet.update(message: message_arr.join(" "))
    return tweet
	end
end

app/views/epicenter/_user_list.html.erb
  <% @users.each do |user| %>
      <div class="container follow-list">
      <div class="pull-left">
        <%= user.name %>
        <%= link_to "@#{user.username}", show_user_path(id: user.id), class: "username" %>
      </div>
      <div class="pull-right">
      <% if current_user.following.include?(user.id) %>
        <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-follow unfollow_btn" %>
      <% else %>
        <% if current_user.id != user.id %>
          <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-follow" %>
        <% end %>
      <% end %>
      </div>
      </div>
      <br>
      
  <% end %>

app/views/epicenter/all_users.html.erb
<h1>All Users</h1>

<%= render "user_list" %>

app/views/epicenter/feed.html.erb
<% if user_signed_in? %>
<div class="container-fluid">
<div class="row">
<div class="col-xs-3" id="user_info">
	<div class="user_info">
		<p><%= current_user.name %></p>
		<p><span class="username"><%= link_to "@#{current_user.username}", show_user_path(id: current_user.id) %></span></p>
		<p><%= current_user.email %></p>
		<p><%= current_user.bio %></p>
	</div>
</div>
<div class="col-xs-3"></div>
<div class="col-xs-9 feed">
	<h1>Your Feed</h1>
	<p>Here is what your "friends" are saying:</p>


	<div>
    	<% @following_tweets.each do |tweet| %>
        	<div class="tweet">
	    		<p><%= tweet.user.name %> | <%=  link_to "@#{tweet.user.username}", show_user_path(id: tweet.user.id) %></p>
	    		<p><%= tweet.message.html_safe %></p>
	    		<%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
	    		<%= tweet.created_at.strftime('%b%e') if Time.now - tweet.created_at > 86400 %>
			</div>
			<br>
    	<% end %>
	</div>
</div>
<% else %>
	<div class="container">
	<p>Please Log In or Sign Up to view this site.</p>
	<a href="users/sign_in"><button>Log In</button></a>
	<a href="users/sign_up"><button>Sign Up</button></a>
	</div>
</div>
</div>
<% end %>

app/views/epicenter/followers.html.erb
<h2>Your followers are</h2>

<%= render "user_list" %>

app/views/epicenter/following.html.erb
<center><h2><%= @interested_user.username %> is currently following</h2></center>

<%= render "user_list" %>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<div class="container-fluid">
<div class="row">
<div class="col-xs-3" id="user_info">
    <h1>User Profile</h1>
    <div class="user_info">
    <p><%= @user.name %></p>
    <p><%= link_to "@#{@user.username}", show_user_path(id: @user.id) %>
        <% if current_user.following.include?(@user.id) %>
            <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-danger", id: "unfollow_btn" %>
        <% else %>
            <% if current_user.id != @user.id %>
            <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
            <% end %>
        <% end %>
    </p>
    <p><%= @user.location %></p>
    <p><%= @user.bio %></p>
    <p><%= link_to "Following", following_path(id: @user.id), class: "btn btn-primary btn-follow" %></p>
    <p><%= link_to "Followers", followers_path(id: @user.id), class: "btn btn-primary btn-follow" %></p>
    </div>

    <a href="feed" class="btn btn-primary btn-feed"><span class="btn-color">Back to Your Feed</span></a>


</div>
<div class="col-xs-3"></div>
<div class="col-xs-9 feed">
    <h1><%= @user.name %>'s Tweets</h1>   
    <% if @tweets.empty? %>
        <div class="empty_tweets">This user has not tweeted anything</div>
    <% end %>
    <% @user.tweets.each_with_index do |tweet| %>
        <div class="tweet">
            <p>@<%= @user.username %></p>
            <p><%= tweet.message.html_safe %></p>
            <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
            <%= tweet.created_at.strftime('%b%e') if Time.now - tweet.created_at > 86400 %>
        </div>
        <br>
    <% end %>
</div>
</div>

app/views/epicenter/tag_tweets.html.erb
<div>
	<h2 class="heading"><%= @tag.phrase %></h2>
</div>
<div class="row">
	<% @tag.tweets.order(created_at: :desc).each do |tweet| %>
		<div class="container tweet">
		<p><%= "@#{tweet.user.username}" %></p>
		<p><%= tweet.message.html_safe %></p>
		<%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
	    <%= tweet.created_at.strftime('%b%e') if Time.now - tweet.created_at > 86400 %>
		</div>
		<br>
	<% end %>
</div>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>

          </button>
          <%= link_to "Home", root_path, class: "navbar-brand nav-text" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "New Tweet", new_tweet_path, class: "nav-text" %></li>
            <li><%= link_to "All Users", all_users_path, class: "nav-text" %></li>
            <li><%= link_to "General Feed", tweets_path, class: "nav-text" %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <% if current_user.avatar.blank? == false %>
                    <%= image_tag current_username %><span class="caret"></span>
                  <% end %>
                  @<%= current_user.username %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>

            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% end %>
    <div class="body">
      <%= yield %>
    </div>
  </body>

</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="well tweet">
    <div class="field">
      <%= form.label "Your Tweet" %>
      <%= form.text_field :message, class: "well tweet" %>
    </div>

    <div class="field">
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="container-fluid">
<div class="col-xs-2"></div>

<div class="col-xs-8">
<h1>General Feed</h1>

  <% @tweets.each do |tweet| %>
    <div class="tweet_general">
    <p><%= tweet.user.name %> | 
    <%= link_to "@#{tweet.user.username}", show_user_path(id: tweet.user.id) %></p>
    <p><%= tweet.message.html_safe %></p>
    <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
    <%= tweet.created_at.strftime('%b%e') if Time.now - tweet.created_at > 86400 %>
    <div class="pull-right">
    <% if current_user.id == tweet.user_id %>
        <%= link_to 'Edit', edit_tweet_path(tweet) %>
        <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    </div>
    </div>
    <br>
  <% end %>

<br>
</div>
<div class="col-xs-2"></div>
</div>
</div>
<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.message.html_safe %>
</p>

<p>
    <strong>User:</strong>
    <%= link_to @tweet.user.username, 
       show_user_path(id: @tweet.user.id) %>
</p>
<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>